plugins:
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: obstacles,        type: "costmap_2d::VoxelLayer"}

publish_frequency: 1.0
obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.15, -0.2], [-0.15, 0.2], [0.3, 0.2],[0.35, 0.0], [0.3, -0.2]]
inflation_radius: 0.55
obstacles:
    observation_sources: base_scan
    base_scan: {data_type: LaserScan, sensor_frame: laser, clearing: true, marking: true, topic: /rover/scan}
